### ISSUE TITLE
配色风格

### ISSUE THREAD

**Issue by Janspiry** [isLinXu/model-metrics-plot#2]
作者你好，感谢你开源这个工具。
我想问下，Paddle绘图的颜色风格是如何实现的呢？，默认代码并不能完成这种绘图。

**Comment by isLinXu** [comment]
你好，Paddle的绘图是他们专门定制的飞桨蓝，颜色色值是用取色器转换成#xxxx来实现的

**Comment by Janspiry** [comment]
明白，十分感谢
